// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: forms.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Schema             string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	AdditionalBackends []string `protobuf:"bytes,4,rep,name=additional_backends,json=additionalBackends,proto3" json:"additional_backends,omitempty"`
}

func (x *GRPCForm) Reset() {
	*x = GRPCForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCForm) ProtoMessage() {}

func (x *GRPCForm) ProtoReflect() protoreflect.Message {
	mi := &file_forms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCForm.ProtoReflect.Descriptor instead.
func (*GRPCForm) Descriptor() ([]byte, []int) {
	return file_forms_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCForm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCForm) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GRPCForm) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *GRPCForm) GetAdditionalBackends() []string {
	if x != nil {
		return x.AdditionalBackends
	}
	return nil
}

var File_forms_proto protoreflect.FileDescriptor

var file_forms_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a,
	0x08, 0x47, 0x52, 0x50, 0x43, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x12, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forms_proto_rawDescOnce sync.Once
	file_forms_proto_rawDescData = file_forms_proto_rawDesc
)

func file_forms_proto_rawDescGZIP() []byte {
	file_forms_proto_rawDescOnce.Do(func() {
		file_forms_proto_rawDescData = protoimpl.X.CompressGZIP(file_forms_proto_rawDescData)
	})
	return file_forms_proto_rawDescData
}

var file_forms_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_forms_proto_goTypes = []interface{}{
	(*GRPCForm)(nil), // 0: GRPCForm
}
var file_forms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forms_proto_init() }
func file_forms_proto_init() {
	if File_forms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GRPCForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forms_proto_goTypes,
		DependencyIndexes: file_forms_proto_depIdxs,
		MessageInfos:      file_forms_proto_msgTypes,
	}.Build()
	File_forms_proto = out.File
	file_forms_proto_rawDesc = nil
	file_forms_proto_goTypes = nil
	file_forms_proto_depIdxs = nil
}
